Ji4 languagesupport
Junkfood-dk/JunkFoodAdmin pull request #22
Opened 2024-03-05 15:00 UTC by palleBrandt

2024-03-06 12:31 UTC, Maquidos approved these changes

2024-03-06 12:32 UTC, allanzigge commented on lib/l10n/app_da.arb
Should description be in danish as well...?

2024-03-06 12:33 UTC, allanzigge requested changes
At least for best practice - don't know if it actually affects things

2024-03-07 05:35 UTC, palleBrandt commented on lib/l10n/app_da.arb
Good point, I'll take a look at it later today 👍

2024-03-11 08:42 UTC, palleBrandt commented on lib/l10n/app_da.arb
I have looked into this. The description is not for accessibility, but only for developers to know where to use the given key in the application. Therefore I suggest keeping it in English.

2024-03-11 08:43 UTC, allanzigge commented on lib/l10n/app_da.arb
*tommel op*

2024-03-11 08:43 UTC, allanzigge approved these changes

2024-03-11 08:43 UTC, merged