Ji 39 chef UI
Junkfood-dk/JunkFoodAdmin pull request #23
Opened 2024-03-09 19:34 UTC by JohanSandager

2024-03-10 20:37 UTC, Maquidos requested changes

2024-03-10 20:37 UTC, Maquidos commented on adr/Dish-posting-state-handeling.md
> +The reason only `fetchDishOfTheDay()` notifies listeners, is as to keep one single source of truth. When we post a new dish, it is the database that should hold information about the dish of the day,
og -> or, in line 27

2024-03-10 20:37 UTC, Maquidos commented on adr/Dish-posting-state-handeling.md
> +The reason only `fetchDishOfTheDay()` notifies listeners, is as to keep one single source of truth. When we post a new dish, it is the database that should hold information about the dish of the day,
Kunne man ikke sætte the dish of the day boolean til false kl 21.00 hver dag? Så undergår man at der er nogen der bare kigger på deres telefon og tænker, "nå der er kylling, det fik vi da også igår, nå... whatever". og så ikke refresher siden, men bliver meget forvirret når de så kommer frem og ser at der er gris?

2024-03-11 12:16 UTC, JohanSandager commented on adr/Dish-posting-state-handeling.md
> +The reason only `fetchDishOfTheDay()` notifies listeners, is as to keep one single source of truth. When we post a new dish, it is the database that should hold information about the dish of the day,
Yeah that would be a good idea, will do

2024-03-11 12:17 UTC, JohanSandager commented on adr/Dish-posting-state-handeling.md
> +The reason only `fetchDishOfTheDay()` notifies listeners, is as to keep one single source of truth. When we post a new dish, it is the database that should hold information about the dish of the day,
ty

2024-03-11 12:32 UTC, palleBrandt commented on adr/Dish-posting-state-handeling.md
> +The current implementation consits of two models, [DishModel](../lib/model/dish_model.dart) and [DishOfTheDayModel](../lib/model/dish_of_the_day_model.dart). The DishModel is not in realtion to provi
```suggestion
The current implementation consits of two models, [DishModel](../lib/model/dish_model.dart) and [DishOfTheDayModel](../lib/model/dish_of_the_day_model.dart). The DishModel is not in relation to provider, but acts as the applications implementation of the dish model. It has a set of helper functions, that respectively parses from and to JSON objects, postable to the DB.
```

2024-03-11 12:47 UTC, palleBrandt requested changes
Added a suggestion to fix some typos. Also a comment about private state.

Otherwise looks really good.

2024-03-11 12:47 UTC, palleBrandt commented on lib/pages/post_dish_page.dart
> +class PostDishPageState extends ChangeNotifier {
Maybe make this private? Thinking _postDishPageState

2024-03-17 18:47 UTC, JohanSandager commented on lib/pages/post_dish_page.dart
> +class PostDishPageState extends ChangeNotifier {
Done ty

2024-03-17 20:10 UTC, palleBrandt approved these changes

2024-03-17 21:25 UTC, Maquidos approved these changes

2024-03-18 06:30 UTC, merged