Ji 14 categories
Junkfood-dk/JunkFoodAdmin pull request #33
Opened 2024-03-20 09:56 UTC by OmarSemou

The story JI-14 is now complete and meets the acceptance criteria:
- A dish can have multiple categories 
- A chef should be able to add new categories
- From the input a list of existing tags should be showed somehow

Also added relevant test and language support

2024-03-21 15:39 UTC, Maquidos requested changes
Few minor questions and suggestion, otherwise, very nice!

2024-03-21 15:39 UTC, Maquidos commented on .vscode/settings.json
> -    "FSharp.suggestGitignore": false
ved du hvorfor disse er fjernet?

2024-03-21 15:39 UTC, Maquidos commented on lib/pages/post_dish_page.dart
> +                            builder: (context, postDishState, child) =>
Igennem klassen har vi kaldt postDishState for postDishPageState, så måske vi skulle holde os til det?

2024-03-21 15:43 UTC, OmarSemou commented on .vscode/settings.json
> -    "FSharp.suggestGitignore": false
Det er bare min VS Code der altid kører noget F# når jeg åbner vores projekt op. Den har selv slettet det

2024-03-21 16:10 UTC, OmarSemou commented on lib/pages/post_dish_page.dart
> +                            builder: (context, postDishState, child) =>
Det retter jeg 👍

2024-03-30 21:09 UTC, Maquidos approved these changes

2024-03-30 21:09 UTC, merged